### ISSUE TITLE
[Bug] -  REFERENCES command denied to user

### ISSUE THREAD

**Issue by StoneMcYT** [AlpsBTE/Plot-System#108]
## Description
Just recently bumped a server to 3.0 and getting a database issue

```
[21:11:29 INFO]: ------------------ Plot-System V3.0 ------------------
[21:11:29 INFO]: Starting plugin...
[21:11:29 INFO]: 
[21:11:29 INFO]: [✔] Successfully loaded required dependencies.
[21:11:29 INFO]: [✔] Successfully loaded configuration files.
[21:11:30 INFO]: [✔] Successfully loaded language files.
[21:11:30 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[21:11:30 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[21:11:30 ERROR]: An error occurred while creating database table!
java.sql.SQLSyntaxErrorException: (conn=263366) REFERENCES command denied to user 'plotsystem'@'172.18.0.4' for table 'plotsystem_test.api_keys'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158) ~[?:?]
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
        at com.alpsbte.plotsystem.core.database.DatabaseConnection.createTables(DatabaseConnection.java:124) ~[?:?]
        at com.alpsbte.plotsystem.core.database.DatabaseConnection.InitializeDatabase(DatabaseConnection.java:74) ~[?:?]
        at com.alpsbte.plotsystem.PlotSystem.onEnable(PlotSystem.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: REFERENCES command denied to user 'plotsystem'@'172.18.0.4' for table 'plotsystem_test.api_keys'
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
        ... 18 more
Caused by: java.sql.SQLException: REFERENCES command denied to user 'plotsystem'@'172.18.0.4' for table 'plotsystem_test.api_keys'
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1694) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1556) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
        ... 18 more
[21:11:30 INFO]: [✔] Successfully initialized database connection.
[21:11:30 INFO]: [✔] Successfully registered event listeners.
[21:11:30 INFO]: [✔] Successfully registered commands.
[21:11:30 INFO]: 
[21:11:30 INFO]: Extensions:
[21:11:30 INFO]: - HolographicDisplays (Leaderboards)
[21:11:30 INFO]: 
[21:11:30 INFO]: Update-Checker:
[21:11:30 INFO]: You are using the latest stable version.
[21:11:30 INFO]: 
[21:11:30 INFO]: Enabled Plot-System plugin.
[21:11:30 INFO]: ------------------------------------------------------
[21:11:30 INFO]: > Made by Alps BTE (AT/CH/LI)
[21:11:30 INFO]: > GitHub: https://github.com/AlpsBTE/Plot-System
[21:11:30 INFO]: ------------------------------------------------------
[21:11:30 INFO]: Done (8.619s)! For help, type "help" or "?"
container@pterodactyl~ Server marked as running...
[21:11:30 INFO]: Timings Reset
[21:11:30 INFO]: [HeadDatabase] Could not download database, Attempting to use the backup database!
[21:11:30 INFO]: [DiscordSRV] [JDA] Login Successful!
[21:11:30 WARN]: [DiscordSRV] 
The current build of DiscordSRV is outdated by 313 commits! Get the latest build at your favorite distribution center.
Spigot: https://www.spigotmc.org/resources/discordsrv.18494/
Github: https://github.com/DiscordSRV/DiscordSRV/releases
Direct Download: https://get.discordsrv.com
[21:11:31 INFO]: [Plan] ----------------------------------------
[21:11:31 INFO]: [Plan] New Release (5.5 build 1969) is available https://github.com/plan-player-analytics/Plan/releases
[21:11:31 INFO]: [Plan] ----------------------------------------
[21:11:31 INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[21:11:31 INFO]: (FAWE) Plugin 'WorldGuard' found. Using it now.
[21:11:31 INFO]: (FAWE) Detected class org.bukkit.event.block.BlockExplodeEvent
```

**Comment by LordTuxn** [comment]
Fixed on latest build.
https://jenkins.alps-bte.com/job/PlotSystem/117/
