### ISSUE TITLE
[Bug] - Could not load language file on server start

### ISSUE THREAD

**Issue by tf2mandeokyi** [AlpsBTE/Plot-System#110]
This error message is popping up every time I try starting the spigot server on Windows:
```
[21:26:54 INFO]: ------------------ Plot-System V3.0.2 ------------------
[21:26:54 INFO]: Starting plugin...
[21:26:54 INFO]:
[21:26:54 INFO]: [?] Successfully loaded required dependencies.
[21:26:54 INFO]: [?] Successfully loaded configuration files.
[21:26:54 INFO]: [X] Could not load language file.
[21:26:54 ERROR]: -1
java.lang.ArrayIndexOutOfBoundsException: -1
		at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_252]
		at java.util.ArrayList.set(ArrayList.java:450) ~[?:1.8.0_252]
		at com.alpsbte.plotsystem.utils.io.YamlFileFactory.updateFile(YamlFileFactory.java:148) ~[PlotSystem-3.0.2-SNAPSHOT.jar:?]
		at com.alpsbte.plotsystem.utils.io.language.LangUtil.lambda$new$0(LangUtil.java:37) ~[PlotSystem-3.0.2-SNAPSHOT.jar:?]
		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_252]
		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_252]
		at com.alpsbte.plotsystem.utils.io.language.LangUtil.<init>(LangUtil.java:33) ~[PlotSystem-3.0.2-SNAPSHOT.jar:?]
		at com.alpsbte.plotsystem.PlotSystem.onEnable(PlotSystem.java:107) [PlotSystem-3.0.2-SNAPSHOT.jar:?]
		at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [server.jar:git-Spigot-79a30d7-f4830a1]
		at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-79a30d7-f4830a1]
		at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-79a30d7-f4830a1]
		at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-79a30d7-f4830a1]
		at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-79a30d7-f4830a1]
		at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-79a30d7-f4830a1]
		at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-79a30d7-f4830a1]
		at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-79a30d7-f4830a1]
		at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-79a30d7-f4830a1]
		at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[21:26:54 INFO]: [Plot-System] Disabling Plot-System v3.0.2
[21:26:54 INFO]:
[21:26:54 INFO]: Disabling plugin...
[21:26:54 INFO]: ------------------------------------------------------
```

How can I fix this?

(PS: I did my best debugging and found out that [`YamlFile#getDefaultFileStream()`](https://github.com/AlpsBTE/Plot-System/blob/0bc53bbd62bdd986d4e724c6bab5faf1aa5c885b/src/main/java/com/alpsbte/plotsystem/utils/io/YamlFile.java#L53) were returning `null` while trying to get the language file resources contained in the JAR file)

**Comment by LordTuxn** [comment]
Hey, thanks for the bug report. I will check it out tomorrow if I get time. We have never tested it on Windows, so it's not unlikely that there could be some issues. 
Have you already tried to delete the language files in the config?

**Comment by tf2mandeokyi** [comment]
Yes, and it didn't fix the issue.

Additionally, while debugging, I found that the plugin wasn't able to read resource files in the JAR file while having no problems reading files in the config folder.

**Comment by LordTuxn** [comment]
Fixed in latest release https://github.com/AlpsBTE/Plot-System/commit/7427ae0ef98fbe0e5b0b730c3b31eeaf6d193e1d
