### ISSUE TITLE
[Bug] - Error while enabling plugin

### ISSUE THREAD

**Issue by axolotlagatsuma** [AlpsBTE/Plot-System#130]
## Description
 ``` 
[15:55:44 INFO]: [Plot-System] Enabling Plot-System v4.0
[15:55:44 ERROR]: Error occurred while enabling Plot-System v4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: li/cinnazeyy/langlibs/core/file/YamlFileFactory
	at com.alpsbte.plotsystem.PlotSystem.onEnable(PlotSystem.java:79) ~[PlotSystem-4.0-129.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: li.cinnazeyy.langlibs.core.file.YamlFileFactory
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 13 more
[15:55:44 INFO]: [Plot-System] Disabling Plot-System v4.0
[15:55:44 INFO]: 
[15:55:44 INFO]:  Disabling plugin... 
[15:55:44 INFO]:  ------------------------------------------------------ 
[15:55:44 INFO]:  >  Made by  Alps BTE (AT/CH/LI) 
[15:55:44 INFO]:  >  GitHub:  https://github.com/AlpsBTE/Plot-System 
[15:55:44 INFO]:  ------------------------------------------------------  
```
## Steps to Reproduce
1.  Add the plugin to 1.20.1 
2.  Start
3.  See error

**Comment by axolotlagatsuma** [comment]
Sorry for my dumbness, this is related to something else.
