### ISSUE TITLE
[Bug] - Custom heads in menus are randomly null

### ISSUE THREAD

**Issue by LordTuxn** [AlpsBTE/Plot-System#57]
Very rare bug in which the heads of HeadDatabase are null.

```
java.lang.NullPointerException: null
        at com.alpsbte.plotsystem.utils.items.builder.ItemBuilder.<init>(ItemBuilder.java:41) ~[?:?]
        at com.alpsbte.plotsystem.core.menus.CompanionMenu.getSelectedDifficultyItem(CompanionMenu.java:305) ~[?:?]
        at com.alpsbte.plotsystem.core.menus.CompanionMenu.setMenuItemsAsync(CompanionMenu.java:130) ~[?:?]
        at com.alpsbte.plotsystem.core.menus.AbstractMenu.lambda$reloadMenuAsync$0(AbstractMenu.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by LordTuxn** [comment]
ig it should be fixed
