### ISSUE TITLE
[Bug] - SFTP Alogrthims 

### ISSUE THREAD

**Issue by StoneMcYT** [AlpsBTE/Plot-System#96]
## Description
Plotsystem seems to not be compatible with pterodactyl panels SFTP system?

```
[19:55:58 INFO]: StoneMcYT issued server command: /plotsystem-terra:createplot
[19:56:01 INFO]: Connecting to vps-b39d9702.REDACTED port 2022
[19:56:01 INFO]: Connection established
[19:56:01 INFO]: Remote version string: SSH-2.0-Go
[19:56:01 INFO]: Local version string: SSH-2.0-JSCH-0.1.54
[19:56:01 INFO]: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
[19:56:01 INFO]: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
[19:56:01 INFO]: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[19:56:01 INFO]: SSH_MSG_KEXINIT sent
[19:56:01 INFO]: SSH_MSG_KEXINIT received
[19:56:01 INFO]: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1
[19:56:01 INFO]: kex: server: ssh-ed25519
[19:56:01 INFO]: kex: server: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[19:56:01 INFO]: kex: server: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[19:56:01 INFO]: kex: server: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
[19:56:01 INFO]: kex: server: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
[19:56:01 INFO]: kex: server: none
[19:56:01 INFO]: kex: server: none
[19:56:01 INFO]: kex: server: 
[19:56:01 INFO]: kex: server: 
[19:56:01 INFO]: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
[19:56:01 INFO]: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[19:56:01 INFO]: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
[19:56:01 INFO]: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
[19:56:01 INFO]: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
[19:56:01 INFO]: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
[19:56:01 INFO]: kex: client: none
[19:56:01 INFO]: kex: client: none
[19:56:01 INFO]: kex: client: 
[19:56:01 INFO]: kex: client: 
[19:56:01 INFO]: Disconnecting from vps-b39d9702.REDACTED port 2022
[19:56:01 ERROR]: An error occurred while uploading schematic file to SFTP/FTP server!
 org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "sftp://stonemc.2b39f618:***@vps-b39d9702.REDACTED:2022/".
        at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.createSession(SftpFileProvider.java:73) ~[?:?]
        at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.doCreateFileSystem(SftpFileProvider.java:94) ~[?:?]
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:93) ~[?:?]
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:72) ~[?:?]
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:56) ~[?:?]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:716) ~[?:?]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:653) ~[?:?]
        at com.alpsbte.plotsystemterra.utils.FTPManager.uploadSchematic(FTPManager.java:54) ~[?:?]
        at com.alpsbte.plotsystemterra.core.plotsystem.PlotCreator.lambda$Create$0(PlotCreator.java:158) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_312]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312]
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "vps-b39d9702.REDACTED".
        at org.apache.commons.vfs2.provider.sftp.SftpClientFactory.createConnection(SftpClientFactory.java:163) ~[?:?]
        at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.createSession(SftpFileProvider.java:66) ~[?:?]
        ... 14 more
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
        at com.jcraft.jsch.Session.receive_kexinit(Session.java:590) ~[?:?]
        at com.jcraft.jsch.Session.connect(Session.java:320) ~[?:?]
        at com.jcraft.jsch.Session.connect(Session.java:183) ~[?:?]
        at org.apache.commons.vfs2.provider.sftp.SftpClientFactory.createConnection(SftpClientFactory.java:161) ~[?:?]
        at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.createSession(SftpFileProvider.java:66) ~[?:?]
        ... 14 more
[19:56:01 ERROR]: An error occurred while saving new plot to database!
 java.io.IOException: null
        at com.alpsbte.plotsystemterra.core.plotsystem.PlotCreator.Create(PlotCreator.java:163) ~[?:?]
        at com.alpsbte.plotsystemterra.core.plotsystem.CreatePlotMenu.lambda$null$5(CreatePlotMenu.java:112) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_312]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312]

```

**Comment by LordTuxn** [comment]
It looks like our SFTP library doesn't support your SFTP Server Algorithm... maybe take a look at this, could fix the issue 
https://stackoverflow.com/questions/30846076/jsch-algorithm-negotiation-fail

**Comment by StoneMcYT** [comment]
> It looks like our SFTP library doesn't support your SFTP Server Algorithm... maybe take a look at this, could fix the issue https://stackoverflow.com/questions/30846076/jsch-algorithm-negotiation-fail

Well as im using  pterodactyl  it seams like their docker container manger thing (Wings) does not depend on the ssh config and has its own thing

**Comment by Zoriot** [comment]
FTP is gone in the current rework. So not needed
